[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/meta/cryptoteddies/editions/:dna"
  to = "/.netlify/functions/cryptoteddies-editions/:dna"
  status = 200

[[redirects]]
  from = "/meta/cryptoteddies/:tokenId"
  to = "/.netlify/functions/cryptoteddies-metadata/:tokenId"
  status = 200

[[redirects]]
  from = "/honeyjar/:id"
  to = "/.netlify/functions/honeyjar-metadata"
  status = 200